services:
  eco_garden_co:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eco_garden_co
    working_dir: /var/www/symfony
    volumes:
      - ./:/var/www/symfony
    ports:
      - "8000:8000"
    networks:
      - local

networks:
  eco_garden_co_network:
    name: eco_garden_co_network
    external: true
  local:
    name: local
    external: true
