services:
  green_goodies:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: green_goodies
    working_dir: /var/www/symfony
    volumes:
      - ./:/var/www/symfony
    ports:
      - "8000:8000"

  green_goodies_database:
    image: postgres:17.2-alpine
    container_name: green_goodies_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ss1234
      POSTGRES_DB: example
    ports:
      - "8989:5432"
    volumes:
      - ./pgsql-database:/var/lib/postgresql/data

  green_goodies_mailpit:
    image: axllent/mailpit
    container_name: green_goodies_mailpit
    restart: always
    ports:
      - "1080:8025"
      - "1025:1025"
